### ISSUE TITLE
Diseño

### ISSUE THREAD

**Issue by josearpa123** [josearpa123/task-manager-app#2]
-modificar signup.html
  *Agregar boton
-main.css
  *Mejorar diseño de index.html y signup.html
    *centrar botones
    *aplicar estilos en el boton agregador en signup.css
    *cuadro para que sobresalga el formulario 
    *volar imaginacion 
    *Diseñar logo y ponerlo como icono

**Comment by JhoanGruezo** [comment]
pongamoslo a milton

**Comment by josearpa123** [comment]
Poner alertas

**Comment by josearpa123** [comment]
agregar en task.html donde ponga nombre de usuario y correo  @JhoanGruezo 
yo en la logica ya me encargo de que funcione
